services:
  db:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db

  web:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    command: "uvicorn --host 0.0.0.0 --port 8000 main:app"
    env_file:
      - .env

volumes:
  mongo_db:
    driver: local